apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: smseagle-proxy
  description: ewdsa
  annotations:
    backstage.io/linguist: 
spec:
  type: service
  lifecycle: production
  owner: group:default/skip