apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test"
  description: "testerr"
  annotations:
    backstage.io/linguist: https://github.com/Kartverket/smseagle-proxy
spec:
  type: "service"
  lifecycle: production
  owner: "group:default/me"
  system : "SKIP"
