apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "skyline"
  description: 
  annotations:
    backstage.io/linguist: https://github.com/kartverket/skyline
spec:
  type: service
  lifecycle: production
  owner: 