apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: smseagle-proxy
  description: Integrates Grafana Oncall with SMSEagle
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: SKIP
  system: SKIP
