apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: smseagle-proxy
  description: asdf
  annotations:
    backstage.io/linguist: https://github.com/kartverket/smseagle-proxy
spec:
  type: service
  lifecycle: production
  owner: group:default/skip