version: "3.7"
services:
  app:
    image: ghcr.io/kartverket/smseagle-proxy:0.0.8-SNAPSHOT-6c7dc64
    ports: ["8080:8080"]
    volumes:
      - type: bind
        source: ./config.yaml
        target: /opt/smseagle-proxy/config.yaml