name: Publish TechDocs Site

on:
  push:


jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
      - id: 'techdocs-action'
        uses: kartverket/backstage-techdocs-action@v1
        with:
          entity_kind: component
          entity_name: smseagle-proxy
          gcs_bucket_name: techdocsxjnci8m15r
          workload_identity_provider: //iam.googleapis.com/projects/833464919209/locations/global/workloadIdentityPools/backstage-techdocs-pool/attribute.enteprise/kartverket
          service_account: techdocs-writer@utviklerportal-sandbox-5af9.iam.gserviceaccount.com
          project_id: ${{vars.BACKSTAGE_TECHDOCS_PROJECT_ID}}
